### ISSUE TITLE
Multiple repositories

### ISSUE THREAD

**Issue by johannesloetzsch** [fzakaria/mvn2nix#22] opened 2020-08-28 22:34 UTC
I don't see how the current implementation is working with multiple ` --repositories` arguments.
According to the documentation of picocli the correct invocation should look like
```shell
mvn2nix --repositories https://clojars.org/repo https://repo1.maven.org/maven2 > dependencies.nix
```
This however causes an error message „Failed to execute goals [[package]].“

Looking deeper into picocli, there seems to be an breaking change since its version 2.0:
Options of type String have now the [default-arity 1](https://picocli.info/#_default_arity) and so the arity needs to be explicitly specified.

**Comment by fzakaria** [comment] 2020-08-28 22:52
hey @johannesloetzsch i think the problem is that `--repositories` needs to be listed more than once.

**Comment by fzakaria** [comment] 2020-08-28 22:55
Here is a concrete example
```bash
mvn2nix --repository https://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases --repository  https://repo.maven.apache.org/maven2
```

**Comment by fzakaria** [comment] 2020-08-28 22:58
Fixed by #23

**Closed by fzakaria** 2020-08-28 22:58 UTC

**Comment by johannesloetzsch** [comment] 2020-08-28 23:11
Thanks for the fast reply and all your work on this usefull tool :)

**Comment by fzakaria** [comment] 2020-08-28 23:15
@johannesloetzsch i appreicate the contribution.
Please be warned; i just merged a change to output JSON instead.

I'm doing still active development on the tool and hope to stabilize it within the week.
If you'd like to avoid that, consider pinning to a commit in the meantime :)

**Comment by johannesloetzsch** [comment] 2020-08-28 23:42
Yes, I realized, but thanks for the hint. Like that you changed it to json and great that it's under development :)

There is just a tiny regression I would suggest to be changed:
mvn2nix takes a bit to run on projects with many dependencies. At the moment the user sees no progress happening and it feels quite unresponsive. Would be nice if you could again add some (optional) logging showing which artifact is processed.

**Comment by fzakaria** [comment] 2020-08-29 20:02
@johannesloetzsch you can toggle `-v` to show more information which is written to STDERR (so you can `> mvn2nix-lock.json`).
I thought the UNIX philosophy was write nothing to STDERR in "the happy case".
Happy to iterate on the ergonomics of it though.
